import test from 'node:test';
import assert from 'node:assert/strict';
import { mainCommandFixture } from './fixtures/main-command-runtime.ts';
import { bindSharedSessionRandom } from './fixtures/shared-session-random.ts';
import { constants as K } from '../src/generated/source-data.ts';
function done<T>(g:Generator<string,T,void>):T{for(let i=0;i<30000;i++){const step=g.next();if(step.done)return step.value;}throw new Error('setup schedule exhausted');}
function fixture(input='\nNO\nNO\nFEDERATION\nLEXINGTON\n'){
  const f=mainCommandFixture(''),b=f.main.setup,a=f.main.admission;f.editor.bytes.length=0;f.editor.feed(input);
  f.high.write('tim0',-1n);f.high.write('numply',0n);f.high.write('numsid',0n,1);f.high.write('numsid',0n,2);
  f.clock.splice(0,f.clock.length,1000n,1001n,1002n,1003n,1004n);f.jobStatus.ppns.push(9n,9n);a.runs.push(1n);
  Object.assign(a.trapAddresses,{zero:0n,cc1:59980n,cc2:59981n,clrbuf:59982n});b.policy.missingTrap=0n;
  bindSharedSessionRandom(f,function*(raw){return f.rawPower.encode({n:raw,d:1n<<27n});}); // Explicit rational FSC fixture.
  return {...f,b,a,setup:()=>done(f.main.setupAndPlace())};
}
function counts(f:ReturnType<typeof fixture>){const count=Array<number>(11).fill(0);for(let v=1;v<=K.KGALV;v++)for(let h=1;h<=K.KGALH;h++)count[Math.trunc(f.views.high.board.disp(v,h)/100)]++;return count;}
test('Fresh SETUP creates full galaxy, admits player, places ship and runs main STATUS',()=>{const f=fixture('\nNO\nNO\nFEDERATION\nLEXINGTON\nSTATUS\n');f.setup();const n=counts(f);assert.equal(n[3],10);assert.equal(n[4],10);assert.equal(n[6],60);assert.equal(n[9],Number(f.m.read(f.b.locals.nstar)));assert.equal(n[10],0);assert.equal(n[1],1);assert.equal(f.high.read('numply'),1n);assert.equal(f.high.read('nplnet'),60n);assert.equal(f.high.read('numsid',1),1n);assert.equal(f.high.read('romopt'),0n);assert.equal(f.high.read('blhopt'),0n);assert.equal(f.high.read('base',1,4,1),1n);assert.equal(f.high.read('base',1,4,2),2n);f.run();assert.ok(f.reports[0].includes('T10 E5000'));});
test('SETUP enables optional Romulan and actually places black holes',()=>{const f=fixture('\nYES\nYES\nFEDERATION\nLEXINGTON\n');f.setup();assert.equal(f.high.read('romopt'),-1n);assert.equal(f.high.read('rom'),0n);assert.equal(f.high.read('blhopt'),-1n);assert.equal(counts(f)[10],Number(f.m.read(f.b.locals.nhole)));});
test('SETUP tournament reseeds from TKNLST word, then repeats same galaxy',()=>{function run(){const f=fixture('TOURNAMENT 123\nNO\nNO\nFEDERATION\nLEXINGTON\n'),gtkn=f.b.io.gtkn;let seed=0n;f.b.io.gtkn=function*(){yield*gtkn();if(f.low.read('ntok')===2n)seed=f.low.read('tknlst',2);};f.setup();return {f,seed};}const a=run(),b=run();assert.ok(a.f.b.events.includes('setran:'+ (a.seed<0n?-a.seed:a.seed)));assert.equal(a.f.b.events.filter(x=>x.startsWith('setran:')).length,2);assert.equal(a.f.file.read('seed'),b.f.file.read('seed'));assert.deepEqual(counts(a.f),counts(b.f));});
test('SETUP later player preserves existing galaxy and skips random generation',()=>{const f=fixture('FEDERATION\nLEXINGTON\n');f.high.write('tim0',10n);f.high.write('numply',1n);f.high.write('nplnet',7n);f.high.write('alive',1n,1);f.high.write('romopt',-1n);f.high.write('blhopt',-1n);f.setup();assert.equal(f.high.read('nplnet'),7n);assert.equal(f.high.read('numply'),2n);assert.ok(f.b.events.includes('setu06'));assert.ok(f.b.events.includes('setu07'));assert.equal(f.b.events.includes('starCount'),false);assert.equal(f.b.events.includes('setqh'),false);});
test('SETUP REGULAR two-label compiler branch remains required',()=>{const f=fixture('REGULAR\n');assert.throws(f.setup,/two-label REGULAR compiler policy/);assert.equal(f.b.events.includes('starCount'),false);});
test('SETUP repeats unrecognized game type with explicit branch policy',()=>{const f=fixture('INVALID\nREGULAR\nNO\nNO\nFEDERATION\nLEXINGTON\n');f.b.policy.regular='true-first';f.setup();assert.equal(f.b.events.filter(x=>x==='setu02').length,2);assert.equal(f.high.read('nplnet'),60n);});
test('SETUP full capacity uses KILHGH and START before lock or player increment',()=>{const f=fixture('');f.high.write('numply',BigInt(K.KNPLAY));f.high.write('dead',1n);f.b.policy.start=function*(){throw new Error('START transfer');};assert.throws(f.setup,/START transfer/);assert.ok(f.b.events.includes('setu01'));assert.ok(f.b.events.includes('kilhgh'));assert.equal(f.b.events.includes('lock'),false);assert.equal(f.high.read('numply'),BigInt(K.KNPLAY));});
test('SETUP ended existing galaxy exits before admission',()=>{const f=fixture('');f.high.write('tim0',10n);f.high.write('numply',1n);f.high.write('endflg',-1n);f.high.write('dead',1n);assert.throws(f.setup,/SETUP EXIT transfer/);assert.ok(f.b.events.includes('nogal1'));assert.equal(f.b.events.includes('admit'),false);assert.equal(f.high.read('numply'),2n);});
test('SETUP cancellation at Regular prompt still initializes world before CC1 exit',()=>{const f=fixture('\n'),gtkn=f.b.io.gtkn;f.b.io.gtkn=function*(){yield*gtkn();f.low.write('ccflg',-1n);};assert.throws(f.setup,/SETUP EXIT transfer/);assert.equal(f.high.read('nplnet'),60n);assert.equal(f.high.read('numply'),0n);assert.equal(f.b.events.includes('setu04'),false);assert.equal(f.b.events.includes('setu05'),false);assert.equal(f.high.read('numsid',1),0n);});
test('SETUP forces disabled sequence check by clearing JSQTIM only',()=>{const f=fixture();f.m.write(f.getHit.queues.address('jsqtim'),999n);delete f.b.policy.missingTrap;assert.throws(f.setup,/zero-argument CCTRAP binding/);assert.equal(f.m.read(f.getHit.queues.address('jsqtim')),0n);assert.equal(f.high.read('numply'),0n);});
