import test from 'node:test';
import assert from 'node:assert/strict';
import { mainCommandFixture } from './fixtures/main-command-runtime.ts';
import { constants as K } from '../src/generated/source-data.ts';
import { packAscii,signed36 } from '../src/compat/word36.ts';
function done<T>(g:Generator<string,T,void>):T{for(let i=0;i<4000;i++){const n=g.next();if(n.done)return n.value;}throw new Error('admission schedule exhausted');}
function fixture(input='FEDERATION\nLEXINGTON\n'){
  const f=mainCommandFixture(''),a=f.main.admission;f.editor.bytes.length=0;f.editor.feed(input);f.low.write('who',0n);
  for(const key of ['numsid','numshp'] as const)for(let i=1;i<=2;i++)f.high.write(key,0n,i);
  for(let i=1;i<=K.KNPLAY;i++){f.high.write('alive',1n,i);f.high.write('job',9600n,i,K.KTTYSP);}
  f.high.write('nkill',0n);f.high.write('numply',1n);f.locks.write('frebie',0n);
  Object.assign(a.trapAddresses,{zero:0n,cc1:59980n,cc2:59981n,clrbuf:59982n});a.runs.push(123n);
  return {...f,a,admit:()=>done(a.run())};
}
function returning(f:ReturnType<typeof fixture>,ship=1,team=1){const id=f.a.locals.identity;f.high.write('nkill',1n);f.high.write('kilque',f.m.read(id),1,1);f.high.write('kilque',f.m.read(id+3n),1,2);f.high.write('kilque',BigInt(ship)*0o1000000n+BigInt(team),1,5);}
test('Admission selects and commissions a ship in the shared game state',()=>{const f=fixture();f.high.write('score',999n,1,1);f.admit();assert.equal(f.low.read('who'),1n);assert.equal(f.low.read('team'),1n);assert.equal(f.high.read('numsid',1),1n);assert.equal(f.high.read('numshp',1),1n);assert.equal(f.high.read('alive',1),-1n);assert.equal(f.high.read('score',1,1),0n);assert.equal(f.high.read('shpcon',1,K.KSNRGY),50000n);assert.equal(f.high.read('shpcon',1,K.KNTORP),10n);assert.equal(f.high.read('job',1,K.KRUNTM),123n);assert.ok(f.text().includes('These vessels are available:'));assert.ok(f.text().includes('This is mission #1 for the'));assert.ok(f.a.events.indexOf('unlock')<f.a.events.indexOf('updcap'));assert.ok(f.statistics.writes.length>0);});
test('Admission creates original team-dependent radio groups',()=>{const f=fixture();f.admit();assert.equal(f.low.read('group',1,1),signed36(packAscii('ALL')));assert.equal(f.low.read('group',1,2),0o1777n);assert.equal(f.low.read('group',6,2),0o37n);assert.equal(f.low.read('group',7,2),0o1740n);});
test('Admission balances sides without asking when counts differ by two',()=>{const f=fixture('COBRA\n');f.high.write('numsid',2n,1);f.admit();assert.equal(f.low.read('team'),2n);assert.equal(f.a.events.includes('setu18'),false);});
test('Admission reuses returning captain ship without selection prompts',()=>{const f=fixture('');returning(f);f.admit();assert.equal(f.low.read('who'),1n);assert.equal(f.a.events.includes('setu13'),false);assert.equal(f.a.events.includes('setu18'),false);assert.equal(f.high.read('kilque',1,3),f.m.read(f.a.locals.identity+4n));});
test('Admission rejects unavailable ship then accepts another',()=>{const f=fixture('FEDERATION\nLEXINGTON\nNIMITZ\n');f.high.write('alive',-1n,1);f.admit();assert.equal(f.low.read('who'),2n);assert.equal(f.a.events.filter(x=>x==='setu15').length,1);});
test('Admission lets returning captain choose replacement after reassignment',()=>{const f=fixture('YES\nNIMITZ\n');returning(f);f.high.write('alive',-1n,1);f.admit();assert.equal(f.low.read('who'),2n);assert.ok(f.a.events.includes('reassignedEnd'));});
test('Admission cancellation before team assignment decrements only player count',()=>{const f=fixture();f.low.write('ccflg',-1n);assert.throws(f.admit,/SETUP EXIT transfer/);assert.equal(f.high.read('numply'),0n);assert.equal(f.high.read('numsid',1),0n);assert.equal(f.high.read('numshp',1),0n);});
test('Admission cancellation after side count preserves historical NUMSHP increment',()=>{const f=fixture(),trap=f.a.io.cctrap;f.a.io.cctrap=function*(h){yield*trap(h);if(h==='cc2')f.low.write('ccflg',-1n);};assert.throws(f.admit,/SETUP EXIT transfer/);assert.equal(f.high.read('numply'),0n);assert.equal(f.high.read('numsid',1),0n);assert.equal(f.high.read('numshp',1),1n);});
test('Admission slowest terminal loop includes an unused slot because source tests WHO',()=>{const f=fixture();f.high.write('job',300n,10,K.KTTYSP);f.admit();assert.equal(f.high.read('alive',10),1n);assert.equal(f.m.read(f.a.locals.identity+5n),300n);assert.equal(f.high.read('slwest'),3n);});
test('Admission zero terminal speed overrides slowest pacing back to one',()=>{const f=fixture();f.high.write('job',0n,10,K.KTTYSP);f.admit();assert.equal(f.high.read('slwest'),1n);});
test('Admission refuses unbound control-trap address',()=>{const f=fixture();delete f.a.trapAddresses.cc1;assert.throws(f.admit,/resolved CCTRAP cc1 address/);assert.equal(f.statistics.writes.length,0);});
test('Admission supports defection when returning fleet is full',()=>{const f=fixture('YES\nCOBRA\n');returning(f);f.high.write('numsid',5n,1);f.admit();assert.equal(f.low.read('team'),2n);assert.equal(f.low.read('who'),6n);assert.equal(f.high.read('numsid',1),5n);assert.equal(f.high.read('numsid',2),1n);assert.ok(f.a.events.includes('defect'));assert.equal(f.low.read('group',6,2),0o1740n);});
test('Admission retains partial counts when commissioning fails before reservation',()=>{const f=fixture();f.a.io.updcap=function*(){throw new Error('commission failed');};assert.throws(f.admit,/commission failed/);assert.equal(f.high.read('numsid',1),1n);assert.equal(f.high.read('alive',1),1n);assert.equal(f.a.events.includes('jobsta'),false);});
test('Admission flows through original PLACE and then main STATUS',()=>{const f=fixture('FEDERATION\nLEXINGTON\nSTATUS\n');f.file.write('seed',1n);done(f.main.admitAndPlace());const v=Number(f.high.read('shpcon',1,K.KVPOS)),h=Number(f.high.read('shpcon',1,K.KHPOS));assert.equal(f.views.high.board.disp(v,h),101);assert.equal(f.main.romulan.placement.draws.at(-2),BigInt(v));assert.equal(f.main.romulan.placement.draws.at(-1),BigInt(h));assert.equal(f.locks.read('ftlerr'),f.apr.fatalTarget);f.run();assert.ok(f.main.calls.some(x=>x.routine==='status'));assert.equal(f.high.read('shpcon',1,K.KSNRGY),50000n);});
